### ISSUE TITLE
Just cloned repo, uploaded successfully, but got a blank screen.

### ISSUE THREAD

**Issue by colinta** [atomic-salamander/puzzle_pack#2]
😢 

Anything I can do to help debug?  I'll try to find out where the code is hanging (I assume it's stuck somewhere)

**Comment by colinta** [comment]
I added this code to `setup()`, immediately after `arduboy.start()`

```
  arduboy.setCursor(46, 28);
  arduboy.print("DEBUG");
  arduboy.display();
  while ( 1 ) {}
```

And still just a blank screen.  This is on Arduboy 1 (not dev kit)

**Comment by MLXXXp** [comment]
https://community.arduboy.com/t/atomic-puzzle-pack/459/35

https://github.com/MLXXXp/puzzle_pack

**Comment by colinta** [comment]
👍
